platform :ios, '7.0'
pod 'REFrostedViewController', :git => 'https://github.com/maybe/REFrostedViewController.git', :commit => '1aa8e8f2c6d90a7cf5132070105348c142783147'
pod 'AFNetworking', '~> 2.0'
pod 'FMDB', '~> 2.0'