platform :ios, '7.0'
pod 'REFrostedViewController', :git => 'https://github.com/maybe/REFrostedViewController.git', :commit => '457c1e5287df752369588120e30262bf159221c8'
pod 'AFNetworking', '~> 2.0'
pod 'FMDB', '~> 2.0'
